sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t tekkasit/docker-react -f Dockerfile.dev .

script: 
  - docker run -e CI=true tekkasit/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-ap-southeast-1-511957028095"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
